### ISSUE TITLE
isLaravelTimestamp() misleading and not a valid check

### ISSUE THREAD

**Issue by zKoz210** [Soyhuce/next-ide-helper#84]
<img width="401" alt="image" src="https://user-images.githubusercontent.com/28255085/234406967-5e462aaa-a320-4e34-a395-d7ce8d13530d.png">

what if the developer does an insert() and doesn't update the create and update time? Laravel allows this

<img width="498" alt="image" src="https://user-images.githubusercontent.com/28255085/234407172-93757322-f38f-4a6b-9e53-336cd62bb57d.png">

**Comment by bastien-phi** [comment]
It's true. 

This was done this way because we always ensure that timestamps are inserted in database and don't want to be annoyed handling nullable types.

For now, you can override locally the timestamps columns in the config file : 
```php
return [
    // ...
    'models' => [
        // ...
        'overrides' => [
            User::class => [
                'updated_at' => '?'.Carbon::class,
                'created_at' => '?'.Carbon::class,
            ]
        ],
    ],
    // ...
];
```

You may also write an extension to override resolved type for the timestamps (i.e. a class implementing https://github.com/Soyhuce/next-ide-helper/blob/main/src/Contracts/ModelResolver.php)

If you wish to be able to configure it more easily, feel free to submit a PR.
